version: '3.8'

services:
  # Servicio de MongoDB
  mongodb:
    image: mongo:latest
    container_name: edutrack360-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=edutrack360
    networks:
      - edutrack-network

  # Servicio de Ollama (IA)
  ollama:
    image: ollama/ollama:latest
    container_name: edutrack360-ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - edutrack-network

  # Servicio del servidor (backend)
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    container_name: edutrack360-server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - ollama
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/edutrack360
      - OLLAMA_API_URL=http://ollama:11434
      - JWT_SECRET=your_jwt_secret_key
    volumes:
      - ./server/reports:/app/server/reports
    networks:
      - edutrack-network

  # Servicio del cliente (frontend)
  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    container_name: edutrack360-client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - edutrack-network

# Volúmenes para persistencia de datos
volumes:
  mongodb_data:
  ollama_data:

# Red para comunicación entre servicios
networks:
  edutrack-network:
    driver: bridge
